Repository webpack/webpack-dev-middleware, pull requests merged in 2018-09, with the labels that each got.

#335 refactor(package): remove `path-is-absolute` dependency (`dependencies`)
  lib/fs.js
  lib/util.js
  package-lock.json
  package.json
Labels: semver: patch, status: approved, type: refactor

#337 feat(middleware): expose the memory filesystem to other middlewares (`response.locals.fs`)
  README.md
  lib/middleware.js
  test/tests/server.js
Labels: semver: minor, status: approved, type: feature

#334 fix: replace `url-join` with `path.posix.join`
  lib/middleware.js
  lib/util.js
  package-lock.json
  package.json
  test/tests/util.js
Labels: pr: review, priority: 3 (important), semver: patch, severity: 3 (broken), type: bug
